### PR TITLE
Fix build with 'serde' feature + fix warning + update various dependencies

### PR DESCRIPTION
**Pull request by adrien-bon**
Hey!
Trying to add my little contribution to the porting effort.
If I have the time, I'll have a look into tiles and tilemaps removal after that.
Thanks for your amazing work! :)

### CODE REVIEW

**Comment by adrien-bon** [comment]
Added some logic to maintain a registry for mapping `MainEntity` to `RenderEntity` so we can properly remove entities in the render world.
Kind of naive implementation: there may be a more performant way to do that.

FYI, I'm testing with https://github.com/adrien-bon/bevy_ecs_tiled/pull/45 (notably `map_reload` example)

**Comment by rparrett** [comment]
Thanks for the PR! I'll look at this closer when I get a chance. I'm not sure how much time I'll have over the holiday.

**Comment by rparrett** [comment]
Thanks again for sharing the work.

Working my way through these changes still. I pushed some stuff to my branch which might complicate things here in this PR.

I'd like to understand and be able to test the removal situation a bit better before proceeding there. Wondering if it makes sense to store the mapping on `RenderChunkStorage2d` and add some methods for removing by main-world entity. Maybe using `MainEntity` and `MainEntityHashMap` where applicable. But it may be best to just get something working in a minimal way and tidy up later.

I am mildly annoyed that we would have to maintain this sort of index, but I don't really see any way around it at the moment. I don't think we can get the `RenderEntity` from the main world while extracting the removals because it no longer exists at that point.

**Comment by rparrett** [comment]
Is it possible with observers or component hooks to retrieve the values of removed entities before they leave the world? Seems like it might be. Could potentially pass along the `RenderEntity` stored on the entity instead of the `Entity`. Bevy should already be inserting a `RenderEntity` on the tile in the main world.

**Comment by adrien-bon** [comment]
Rebased the PR on your branch.

I agree with you, I don't like either keeping this `RenderEntity` / `MainEntity` mapping around (and I especially don't like how I construct it).
What I tried was to add a query in `removal_helper_tilemap()` and `removal_helper()` functions to get the `RenderEntity` and propagate it instead of the `MainEntity`. It did not  work: the query never returned anything since I believe the underlying `Entity` was actually already removed at this point.
I'll give a try to components hooks instead, they are maybe called earlier, before the `RenderEntity` component is gone.

**Comment by rparrett** [comment]
I just pushed an obsever-based solution here: https://github.com/rparrett/bevy_ecs_tilemap/commit/c06a01f1314a9987b15f3f3fbe2367ddd4c86d0d

Which seems to work at a glance and feels really clean. I only tested by running the `remove_tiles` example so far though.

**Comment by adrien-bon** [comment]
More removal than insertions, I like that.
I was doing the same kind of change but using hooks instead of observers, but I prefer your solution.

I believe we can drop this PR in favor of your branch.
Can you please also pick commits for fixing warning / compilation with `serde` feature ?

EDIT: commits list

- [fix: compilation with serde feature](https://github.com/rparrett/bevy_ecs_tilemap/pull/5/commits/136cb5a47f1cb1de9ad306504904bd3e2e986967)
- [chore: fix unused var](https://github.com/rparrett/bevy_ecs_tilemap/pull/5/commits/3faf536f8677119e0843eee9391a30b5fd4b9d06)
- [update various dependencies](https://github.com/rparrett/bevy_ecs_tilemap/pull/5/commits/3aadf52d84f0017aa770725eda843b5946fea95f)

EDIT 2: also updated the PR

**Comment by rparrett** [comment]
I'd prefer to leave the dependency updates for a followup unless there's something critical in there, or it's a duplicate due to a bump in Bevy.

**Comment by adrien-bon** [comment]
Ok: fine for me! :)
Closing this PR, let's continue the discussion over https://github.com/StarArawn/bevy_ecs_tilemap/pull/574

**Pull request closed without merging**
